- name: Create Custom facts directory and deploy
  hosts: all
  vars:
    custom_fact_files:
      - name: application.fact
        mode: '644'
      - name: server.fact
        mode: '644'
      - name: apache.fact
        mode: '755'
  tasks:
  - name: "Create facts.d directory"
    ansible.builtin.file:
        path: "/etc/ansible/facts.d"
        state: "directory"

  - name: "copy custom fact bash script"
    ansible.builtin.copy:
        src: "{{ item.name }}"
        dest: /etc/ansible/facts.d/
        mode: "{{ item.mode }}"
    loop: "{{ custom_fact_files }}"
