- name: Create Custom facts directory and deploy
  hosts: all
  vars:
    custom_fact_files:
      - application.fact
      - server.fact
      - apache.fact
  tasks:
  - name: "Create facts.d directory"
    ansible.builtin.file:
        path: "/etc/ansible/facts.d"
        state: "directory"

  - name: "copy custom fact bash script"
    ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/ansible/facts.d/
        mode: 0755
    loop: "{{ custom_fact_files }}"
